server:
  port: 9092

spring:
  application:
    name: hotelservice

#database
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pr0f1nch@1234
#hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#Eureka Discovery Client
eureka:
  client:
    fetch-registry: true
    register-with-eureka : true
    service-url:
      defaultZone : http://localhost:9090/eureka
  instance:
    prefer-ip-address: true